import React, { useState } from 'react';
import CircularProgress from '@mui/material/CircularProgress';
import IconButton from '@mui/material/IconButton';
import { IoDownloadOutline } from 'react-icons/io5';

const SERVER = import.meta.env.VITE_SERVERURL;

const slugify = (text) =>
  String(text || 'invoice')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w-]+/g, '');

// Downloads the invoice PDF generated by the backend (Puppeteer).
const InvoiceDownload = ({ formData, iconSize }) => {
  const [downloading, setDownloading] = useState(false);

  if (!formData) {
    return <CircularProgress size={iconSize} />;
  }

  const handleDownload = async () => {
    try {
      setDownloading(true);

      const res = await fetch(`${SERVER}/api/invoice-pdf`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ data: formData }),
      });

      if (!res.ok) throw new Error(`PDF request failed: ${res.status}`);

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${slugify(formData?.project?.project_name)}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Invoice download error:', err);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <IconButton title="Download PDF file" onClick={handleDownload} disabled={downloading}>
      {downloading ? (
        <CircularProgress size={iconSize} />
      ) : (
        <IoDownloadOutline color="dark" size={iconSize} />
      )}
    </IconButton>
  );
};

export default InvoiceDownload;
