    export const initialValues = {
        email: "",
        phone: "",
        whatsapp: "",
        gender: "male",
        firstName: "",
        lastName: "",
        companyName: "",
        birthday: "",
        textarea: "",
        fileUpload: null,
        consent: false,
        company_partnerBrand:"",
        company_partnerName:"",
        company_cityCountry:"",
        company_phone:"",
        company_mobile:"",
        company_email:"",
        company_website:"",
        company_employeeCount:"",
        company_industry:"",
        company_ceoOwnerGm:"",
        company_ceoOwnerGm_contactNumber:"",
        company_ceoOwnerGm_email:"",
        company_hrHead:"",
        company_hrHead_contactNumber:"",
        company_hrHead_email:"",
        company_accountingHead:"",
        company_accountingHead_contactNumber:"",
        company_accountingHead_email:"",
        company_marketingHead:"",
        company_marketingHead_contactNumber:"",
        company_marketingHead_email:"",
        company_pa:"",
        company_pa_contactNumber:"",
        company_pa_email:"",
    };